### ISSUE TITLE
v3/service-instances test flaking with multiple nodes

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-acceptance-tests#359] opened 2019-02-26 22:28 UTC
I'm running my tests with 5 nodes and I am frequently failing this test.  I'm not 100% sure but it seems this test fails if another node happens to hava a service instance at the same time this test is running.

https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/v3/service_instances.go#L71  Doesn't scope the service instances to a single space and I'm running my tests with `existing_user` set.  So, perhaps it is picking up service instances created in another space because the same user has access to both spaces?

```
• Failure [86.048 seconds]
[v3]
/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:233
  service instances
  /go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:239
    Lists the service instances [It]
    /go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/service_instances.go:65

    Expected
        <[]v3.ServiceInstance | len:4, cap:4>: [
            {
                Name: "CATS-2-SVC-14d010047d26ce62",
            },
            {
                Name: "CATS-1-SVC-8509465cfab60de8",
            },
            {
                Name: "CATS-4-SVIN-8d4f8d3a44eb9d97",
            },
            {
                Name: "CATS-4-SVIN-34e5963b6741ea91",
            },
        ]
    to consist of
        <[]interface {} | len:1, cap:1>: [
            [
                {
                    Name: "CATS-4-SVIN-8d4f8d3a44eb9d97",
                },
                {
                    Name: "CATS-4-SVIN-34e5963b6741ea91",
                },
            ],
        ]

    /go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/service_instances.go:78
```

**Comment by Syerram** [comment] 2019-07-07 19:54
Although there is a PR that scopes the API call to just the current space, we don't recommend running it with an existing user. Please let us know if you're seeing the same issue once you run with a unique user meant for tests only.

**Comment by forbushbl** [comment] 2019-07-08 22:34
@Syerram The problem is when we use the Ginkgo flag to run multiple tests in parallel (i.e. `-nodes=n`) the test user occasionally sees the services being created by other running tests and causes a failure. We are using a test user meant for tests only. This seems like a concurrency bug in the tests which would be solved by the PR which I've submitted.

**Comment by davewalter** [comment] 2019-08-07 18:18
Fixed by merging #379.

**Closed by davewalter** 2019-08-07 18:18 UTC
Labels: in progress
