### ISSUE TITLE
Multiple app ports fails with `Requested route does not exist.`

### ISSUE THREAD

**Issue by combor** [cloudfoundry/cf-acceptance-tests#118] opened 2016-05-23 15:47 UTC
## Issue

The `multiple app ports` test that checks if app that listens on multiple ports can be accessed via alternative route has a race condition as it checks for route existence too quickly, before requested route becomes available.

## Context

This change https://github.com/cloudfoundry/cf-acceptance-tests/commit/7599345cb0822ea199ae36789da7d66a45c8daed#diff-f4bbf55b096c3c1ba009d2212bd93596R46 has moved `UpdatePorts` method to be executed after application starts. Unfortunately UpdatePorts forces Lattice app to restart:
```
2016-05-23T15:48:26.57+0100 [API/0]      OUT Updated app with guid 1904a6cd-7d96-41ef-bfc9-e0be72213d4e ({"ports"=>[7777, 8888, 8080]})
2016-05-23T15:48:26.64+0100 [CELL/0]     OUT Creating container
2016-05-23T15:48:26.82+0100 [APP/0]      OUT Lattice-app. Says Hello. on index: 0
2016-05-23T15:48:26.90+0100 [APP/0]      OUT Lattice-app. Says Hello. on index: 0
2016-05-23T15:48:26.91+0100 [CELL/0]     OUT Successfully created container
2016-05-23T15:48:27.31+0100 [CELL/0]     OUT Starting health monitoring of container
2016-05-23T15:48:27.33+0100 [APP/0]      OUT {"timestamp":"1464014907.332120180","source":"lattice-app","message":"lattice-app.lattice-app.starting","log_level":1,"data":{"ports":["7777","8888","8080"]}}
2016-05-23T15:48:27.33+0100 [APP/0]      OUT {"timestamp":"1464014907.332395792","source":"lattice-app","message":"lattice-app.lattice-app.up","log_level":1,"data":{"port":"8080"}}
2016-05-23T15:48:27.33+0100 [APP/0]      OUT {"timestamp":"1464014907.332480431","source":"lattice-app","message":"lattice-app.lattice-app.up","log_level":1,"data":{"port":"7777"}}
2016-05-23T15:48:27.33+0100 [APP/0]      OUT {"timestamp":"1464014907.332562208","source":"lattice-app","message":"lattice-app.lattice-app.up","log_level":1,"data":{"port":"8888"}}
2016-05-23T15:48:27.82+0100 [APP/0]      OUT Lattice-app. Says Hello. on index: 0
2016-05-23T15:48:27.83+0100 [CELL/0]     OUT Container became healthy
2016-05-23T15:48:27.90+0100 [APP/0]      OUT Lattice-app. Says Hello. on index: 0
2016-05-23T15:48:27.93+0100 [APP/0]      OUT Exit status 2
2016-05-23T15:48:27.93+0100 [CELL/0]     OUT Exit status 0
2016-05-23T15:48:28.07+0100 [CELL/0]     OUT Exit status 0
2016-05-23T15:48:28.07+0100 [APP/0]      OUT Exit status 2
2016-05-23T15:48:28.33+0100 [APP/0]      OUT Lattice-app. Says Hello. on index: 0
2016-05-23T15:48:29.33+0100 [APP/0]      OUT Lattice-app. Says Hello. on index: 0
```

and makes new route not available immediately. 

## Steps to Reproduce

Push and start lattice app with:

```
cf push lattice  -b go_buildpack --no-start -m 256M  -c "lattice-app --ports=7777,8888,8080"
cf start lattice
```
And use this script:
```
#! /bin/bash
YOUR_DOMAIN_NAME="xxx"
AGUID=$(cf app lattice --guid)
cf curl /v2/apps/"${AGUID}" -X PUT -d '{"ports":[7777,8888,8080,6001]}' > /dev/null
cf create-route GDS "${YOUR_DOMAIN_NAME} --hostname lattice-two --path ""
RGUID=$(cf curl '/v2/routes?q=host:lattice-two&q=path:' | awk -F'"' '$2 ~ /^guid/ {print $4}')
cf curl /v2/route_mappings -X POST -d \{\"app_guid\":\"${AGUID}\",\"app_port\":7777,\"route_guid\":\"${RGUID}\"\} > /dev/null
cf curl /v2/apps/$AGUID -X PUT -d '{"ports":[7777,8888,8080]}' > /dev/null
curl -k -s https://lattice-two."${YOUR_DOMAIN_NAME}"/port
```

## Expected result

```
7777
```

## Current result

```
404 Not Found: Requested route ('lattice-two.xxx.digital') does not exist.
```

## Possible Fix

Add sleep ( 20 seconds at least ) after `cf curl /v2/apps/$AGUID -X PUT -d '{"ports":[7777,8888,8080]}' ` or retry request few times to allow lattice to restart.

**Comment by DennisDenuto** [comment] 2016-05-31 20:52
Hi @combor,

We have attempted to reproduce the issue in CATS, we deployed both the latest versions of cf and diego release on bosh-lite running locally and repeatedly ran the suite to see if we could observe a failure but this has not happened. Also the script you provided is functionally different to what the CATS test does (i.e. the CATS test tries to curl the additional port every 5 seconds for up to one minute). One minute should be enough time for the app to start. 

Also if the app has not started yet we would expect to see the test to fail on [these lines](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/routing/multiple_app_ports_test.go#L57-L59), because the app would not respond on either port. If possible could you post the output of the CATS logs (not the script) when you observe the test failing so that we can confirm that our possible fix would even work? 

Thanks,
Dennis & @APShirley

**Comment by DennisDenuto** [comment] 2016-06-15 00:16
Hi @combor,

As we have not heard a response in a while we are going to close this issue for now. If you have any questions or want to pick this back up please open a new issue.

Thanks,
Dennis && @APShirley

**Closed by DennisDenuto** 2016-06-15 00:16 UTC
Labels: unscheduled
