### ISSUE TITLE
Timing issue on Environment Variables Task test

### ISSUE THREAD

**Issue by wbean1** [cloudfoundry/cf-acceptance-tests#218] opened 2017-06-27 18:44 UTC
We recently started having a consistently failing test, which looks to be somewhat new:
```
• Failure [35.633 seconds]
[apps] Default Environment Variables
/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:38
  Default staging environment variables
  /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:179
    applies default environment variables while running apps and tasks [It]
    /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:178

    Expected
        <string>: Connected, dumping recent logs for app CATS-2-APP-11a34b0f-988a-400c-6 in org CATS-2-ORG-c5422bbe-f07a-4ba1-5 / space CATS-2-SPACE-ab57098b-8701-4859-5 as CATS-USER-2-2017_06_27-15h35m04.78s...
        
        2017-06-27T16:38:27.35+0000 [API/0]      OUT Created app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
        2017-06-27T16:38:27.77+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"route"=>"583b3a7a-1942-4944-914b-fade1316bded", :verb=>"add", :relation=>"routes", :related_guid=>"583b3a7a-1942-4944-914b-fade1316bded"})
        2017-06-27T16:38:33.89+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"diego"=>true})
        2017-06-27T16:38:34.58+0000 [API/0]      OUT Creating build for app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
        2017-06-27T16:38:34.70+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"state"=>"STARTED"})
        2017-06-27T16:38:34.73+0000 [STG/0]      OUT Downloading binary_buildpack...
        2017-06-27T16:38:34.74+0000 [STG/0]      OUT Downloaded binary_buildpack
        2017-06-27T16:38:34.74+0000 [STG/0]      OUT Creating container
        2017-06-27T16:38:35.34+0000 [STG/0]      OUT Successfully created container
        2017-06-27T16:38:35.34+0000 [STG/0]      OUT Downloading app package...
        2017-06-27T16:38:35.38+0000 [STG/0]      OUT Downloaded app package (524B)
        2017-06-27T16:38:35.38+0000 [STG/0]      OUT Staging...
        2017-06-27T16:38:35.46+0000 [STG/0]      OUT -------> Buildpack version 1.0.13
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Exit status 0
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Staging complete
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading droplet, build artifacts cache...
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading build artifacts cache...
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading droplet...
        2017-06-27T16:38:35.93+0000 [STG/0]      OUT Uploaded build artifacts cache (202B)
        2017-06-27T16:38:35.94+0000 [API/0]      OUT Creating droplet for app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
        2017-06-27T16:38:40.00+0000 [STG/0]      OUT Uploaded droplet (678B)
        2017-06-27T16:38:40.00+0000 [STG/0]      OUT Uploading complete
        2017-06-27T16:38:40.03+0000 [STG/0]      OUT Destroying container
        2017-06-27T16:38:40.37+0000 [CELL/0]     OUT Creating container
        2017-06-27T16:38:40.37+0000 [STG/0]      OUT Successfully destroyed container
        2017-06-27T16:38:40.79+0000 [CELL/0]     OUT Successfully created container
        2017-06-27T16:38:40.86+0000 [CELL/0]     OUT Starting health monitoring of container
        2017-06-27T16:38:41.21+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  WEBrick 1.3.1
        2017-06-27T16:38:41.21+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux]
        2017-06-27T16:38:41.22+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  WEBrick::HTTPServer#start: pid=6 port=8080
        2017-06-27T16:38:42.95+0000 [CELL/0]     OUT Container became healthy
        2017-06-27T16:38:51.13+0000 [RTR/1]      OUT CATS-2-APP-11a34b0f-988a-400c-6.cflab.ic.deere.com - [2017-06-27T16:38:51.128+0000] "GET /env HTTP/1.1" 200 0 1454 "-" "curl/7.38.0" "204.53.110.1:42226" "10.0.5.10:60810" x_forwarded_for:"204.53.110.1" x_forwarded_proto:"https" vcap_request_id:"e84c9913-1597-4845-7614-c7d07e80528c" response_time:0.007439526 app_id:"771951ae-0f2f-4543-99fa-a3cc66e07be2" app_index:"0"
        
    to match regular expression
        <string>: TASK.*LANG=en_US\.UTF-8

    /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:170
```
It appears from the test output that it does not wait very long (perhaps only 1-2 seconds) after the task is found to be in `SUCCEEDED` state before expecting the output to be in the logs. 

```
[2017-06-27 16:38:52.81 (UTC)]> cf tasks CATS-2-APP-11a34b0f-988a-400c-6 
Getting tasks for app CATS-2-APP-11a34b0f-988a-400c-6 in org CATS-2-ORG-c5422bbe-f07a-4ba1-5 / space CATS-2-SPACE-ab57098b-8701-4859-5 as CATS-USER-2-2017_06_27-15h35m04.78s...
OK

id   name      state       start time                      command
1    get-env   SUCCEEDED   Tue, 27 Jun 2017 16:38:51 UTC   env
```
vs the last check of the log at:
```
[2017-06-27 16:38:54.53 (UTC)]> cf logs CATS-2-APP-11a34b0f-988a-400c-6 --recent 
Connected, dumping recent logs for app CATS-2-APP-11a34b0f-988a-400c-6 in org CATS-2-ORG-c5422bbe-f07a-4ba1-5 / space CATS-2-SPACE-ab57098b-8701-4859-5 as CATS-USER-2-2017_06_27-15h35m04.78s...

2017-06-27T16:38:27.35+0000 [API/0]      OUT Created app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
2017-06-27T16:38:27.77+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"route"=>"583b3a7a-1942-4944-914b-fade1316bded", :verb=>"add", :relation=>"routes", :related_guid=>"583b3a7a-1942-4944-914b-fade1316bded"})
2017-06-27T16:38:33.89+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"diego"=>true})
2017-06-27T16:38:34.58+0000 [API/0]      OUT Creating build for app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
2017-06-27T16:38:34.70+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"state"=>"STARTED"})
2017-06-27T16:38:34.73+0000 [STG/0]      OUT Downloading binary_buildpack...
2017-06-27T16:38:34.74+0000 [STG/0]      OUT Downloaded binary_buildpack
2017-06-27T16:38:34.74+0000 [STG/0]      OUT Creating container
2017-06-27T16:38:35.34+0000 [STG/0]      OUT Successfully created container
2017-06-27T16:38:35.34+0000 [STG/0]      OUT Downloading app package...
2017-06-27T16:38:35.38+0000 [STG/0]      OUT Downloaded app package (524B)
2017-06-27T16:38:35.38+0000 [STG/0]      OUT Staging...
2017-06-27T16:38:35.46+0000 [STG/0]      OUT -------> Buildpack version 1.0.13
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Exit status 0
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Staging complete
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading droplet, build artifacts cache...
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading build artifacts cache...
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading droplet...
2017-06-27T16:38:35.93+0000 [STG/0]      OUT Uploaded build artifacts cache (202B)
2017-06-27T16:38:35.94+0000 [API/0]      OUT Creating droplet for app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
2017-06-27T16:38:40.00+0000 [STG/0]      OUT Uploaded droplet (678B)
2017-06-27T16:38:40.00+0000 [STG/0]      OUT Uploading complete
2017-06-27T16:38:40.03+0000 [STG/0]      OUT Destroying container
2017-06-27T16:38:40.37+0000 [CELL/0]     OUT Creating container
2017-06-27T16:38:40.37+0000 [STG/0]      OUT Successfully destroyed container
2017-06-27T16:38:40.79+0000 [CELL/0]     OUT Successfully created container
2017-06-27T16:38:40.86+0000 [CELL/0]     OUT Starting health monitoring of container
2017-06-27T16:38:41.21+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  WEBrick 1.3.1
2017-06-27T16:38:41.21+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux]
2017-06-27T16:38:41.22+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  WEBrick::HTTPServer#start: pid=6 port=8080
2017-06-27T16:38:42.95+0000 [CELL/0]     OUT Container became healthy
2017-06-27T16:38:51.13+0000 [RTR/1]      OUT CATS-2-APP-11a34b0f-988a-400c-6.cflab.ic.deere.com - [2017-06-27T16:38:51.128+0000] "GET /env HTTP/1.1" 200 0 1454 "-" "curl/7.38.0" "204.53.110.1:42226" "10.0.5.10:60810" x_forwarded_for:"204.53.110.1" x_forwarded_proto:"https" vcap_request_id:"e84c9913-1597-4845-7614-c7d07e80528c" response_time:0.007439526 app_id:"771951ae-0f2f-4543-99fa-a3cc66e07be2" app_index:"0"
<this is where the TASK logs eventually would show up>
```

In our environment (potentially terrible, it is openstack-based...:yolo:) it seems to take 3-4s from after task is in `SUCCEEDED` state til the logging shows up... but it does show up.  I'm not sure if this means something is really slow in aggregating the task container logs, or whats going on, but I'm interested if we're the only ones having issues with this test.

**Comment by dsabeti** [comment] 2017-06-27 22:18
Hi @wbean1. It looks to me like the `Eventually` and `Wait` logic in this test is a little buggy.

First, it looks like [this code here](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/default_environment_variables.go#L163-L167) waits for `cf logs --recent` to exit twice -- first [with this `Wait`](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/default_environment_variables.go#L165), and again [with this `Eventually`](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/default_environment_variables.go#L167).

More importantly, that code fetches logs a single time. Afterwards, the test does a [series of synchronous expectations here](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/default_environment_variables.go#L170-L177).

It probably makes the most sense to make those regex expectations in a retry loop / with an `Eventually` instead. Maybe something like this:
```go
Eventually(func() string {
    appLogsSession = cf.Cf("logs", "--recent", appName)
    appLogsSession.Wait(Config.DefaultTimeoutDuration())
    return string(appLogsSession.Out.Contents())
}, Config.DefaultTimeoutDuration()).Should(MatchRegexp("TASK.*LANG=en_US\\.UTF-8"))

Eventually(func() string {
    appLogsSession = cf.Cf("logs", "--recent", appName)
    appLogsSession.Wait(Config.DefaultTimeoutDuration())
    return string(appLogsSession.Out.Contents())
}, Config.DefaultTimeoutDuration()).Should(MatchRegexp("TASK.*CF_INSTANCE_ADDR=.*"))

...
```

That's a lot of calls to `cf logs --recent`, but at least you'd always know that you were making the regex expectation against the latest logs.

@zrob @Gerg, do you think CAPI could try to fix up these timeout issues?

**Comment by anniesing** [comment] 2017-06-29 17:59
Hi @wbean1. We are interested in diving a bit further into the configuration of your environment. The key we're interested in is called `default_timeout`. What is the value of that for you?

After looking at our own test config, we see that our timeout duration is set to 60. We'd like to verify that your default config timeout duration is set similarly.

To do this, please find the file that your $CONFIG env variable is pointing to. It should be an integration configuration .json file. For more information on setting up this file, see [Test Configuration](https://github.com/cloudfoundry/cf-acceptance-tests#test-configuration) in our Readme. Notice, there are [defaults](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/helpers/config/config_struct.go#L111-L180) set if you don't set them explicitly.

Also, as a workaround, we're curious if you could change the value to 60 and re-run the tests. Do they pass with a higher timeout? If so, we'd love to know. We'll use that to inform our investigation as to why the old timeout is too short.

Thanks,
@anniesing and @tusing

**Comment by wbean1** [comment] 2017-06-29 21:08
Hi @anniesing and @tusing, thank you very much for looking into this.

We are not providing any value for `default_timeout` (or any timeout), so the default is being used.  My reading is that that would be `30`.

I don't think a higher timeout value would help here as the code uses that timeout only for setting how long commands should wait to exit.  I view the problem as [this Eventually](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/default_environment_variables.go#L158-L160) completes and immediately triggers [this call](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/default_environment_variables.go#L163-L167) to `cf logs <appname> --recent`, which completes quick enough that its somehow before the task logs make it through loggregator.

I will run with a value of `60` and report back.  Thanks again for your time!

side-note: any tips on how to run just this single test (or even just this file of tests?)

**Comment by dsabeti** [comment] 2017-06-29 22:02
@wbean1 You can always add an **F** to the `It` methods to **focus** the test:
```
...
    FIt("applies default environment variables while running apps and tasks", func() {
...
```

**Comment by dsabeti** [comment] 2017-07-07 00:59
Hey @wbean1, did updating the timeouts help?

**Comment by wbean1** [comment] 2017-07-07 16:37
It looks like increasing `default_timeout` to `60` does help, from testing locally.  Shows how well I can decipher these tests...  I'm still trying to verify that its not a difference between running ginkgo with/without the `-p` option,  Will close this out Monday if its just a timeout thing specific to our (possibly slower than normal) environment, since no one else has chimed in with a 'me-too'.

Thanks again for the help.

**Comment by enocom** [comment] 2017-07-10 17:58
We've seen the same issue in Loggregator's pipeline. Our `default_timeout` is already well-above `60` at `120` seconds.

**Comment by wbean1** [comment] 2017-07-10 21:12
Can confirm my local successes with increased `default_timeout` appear to have been random luck.  Our pipeline still fails these tests consistently even with longer timeout.

**Comment by wbean1** [comment] 2017-07-13 13:17
Fix works good, thanks @bradylove @enocom.  I do still get a similar failure with the staging environment variables test from the same test file:
```
• Failure [28.515 seconds]
[apps] Default Environment Variables
/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:38
  Default staging environment variables
  /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:181
    applies default environment variables while staging apps [It]
    /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:115

    Expected
        <string>: Starting app CATS-1-APP-6549b7a2-f9cc-46c0-4 in org CATS-1-ORG-2d665a11-a0de-488e-7 / space CATS-1-SPACE-4c16b5e2-94ac-45a1-5 as CATS-USER-1-2017_07_12-21h12m40.635s...
        Staging app and tracing logs...
           Downloading CATS-1-BPK-2a300481-7384-4d9c-7...
           Downloaded CATS-1-BPK-2a300481-7384-4d9c-7 (447B)
           Creating container
           Successfully created container
           Downloading app package...
           Downloaded app package (246.3K)
           Staging...
           CF_INSTANCE_ADDR=
        FAILED
        
    to match regular expression
        <string>: LANG=en_US\.UTF-8

    /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:106
```
not sure if you've seen the same.

**Comment by dsabeti** [comment] 2017-07-14 16:27
I think this error looks to be pretty similar. `cf start` also follows logs, so it might be a similar issue that you need to wait for `cf logs --recent` to show all the necessary logs.

@wbean1, are you still seeing this error? If so, we should re-open this issue and have RelInt/CAPI work on a fix.

**Comment by crhino** [comment] 2017-07-14 22:59
@dsabeti We are also seeing this test fail in our CI environment. It is pretty consistent, about 6/9 times.

The issue is different then the one solved earlier. This test is not asserting on `cf logs --recent` at all, and instead relies on the environment variables being out put in the `cf start` command. Since the test waits for the `cf start` command to exit, there is no timing issue. The CLI is just not receiving any of the logs.

**Comment by jvshahid** [comment] 2017-07-17 16:51
@dsabeti i think the culprit is [this sleep](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/default_environment_variables.go#L38-L39). Swapping those two lines will fix the issue. It looks like this is a race condition that depends which one is fast, CC task callback or logs through metron. Worth noting that we are only seeing this flake on loggregator v2.

@wbean1 out of curiosity are you using loggregator v2 ?

**Comment by jvshahid** [comment] 2017-07-17 17:11
@wbean1 @swetharepakula and I fixed the issue you mentioned in https://github.com/cloudfoundry/cf-acceptance-tests/issues/218#issuecomment-315074921 on `develop` of https://github.com/cloudfoundry/cf-release. It would great if you can confirm this fixes the issue you are seeing.

**Comment by dsabeti** [comment] 2017-07-27 01:05
We've merged the PR from the Diego team that we think addresses this issue. I'm going to close the issue for now, but feel free to re-open if you see the problem again.

**Closed by dsabeti** 2017-07-27 01:05 UTC
Labels: unscheduled

**Comment by wbean1** [comment] 2017-07-28 13:14
Thanks everyone for the work on this.  Just deployed v268 of cf-release and these tests pass consistently now.
